export const countries = [
  { label: "Australia", value: "Australia" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Nauru", value: "Nauru" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Australia", value: "Australia" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "Guernsey", value: "Guernsey" },
  { label: "Isle of Man", value: "Isle of Man" },
  { label: "Jersey", value: "Jersey" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "Canada", value: "Canada" },
  { label: "Saint Pierre and Miquelon", value: "Saint Pierre and Miquelon" },
  { label: "Canada", value: "Canada" },
  { label: "Canada", value: "Canada" },
  { label: "Canada", value: "Canada" },
  { label: "China", value: "China" },
  { label: "China", value: "China" },
  { label: "China", value: "China" },
  { label: "China", value: "China" },
  { label: "China", value: "China" },
  { label: "Andorra", value: "Andorra" },
  { label: "Austria", value: "Austria" },
  { label: "Belgium", value: "Belgium" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Estonia", value: "Estonia" },
  { label: "India", value: "India" },
  { label: "Nepal", value: "Nepal" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Japan", value: "Japan" },
  { label: "Japan", value: "Japan" },
  { label: "Japan", value: "Japan" },
  { label: "Japan", value: "Japan" },
  { label: "Japan", value: "Japan" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Cook Islands", value: "Cook Islands" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Niue", value: "Niue" },
  { label: "Sweden", value: "Sweden" },
  { label: "Norway", value: "Norway" },
  { label: "Finland", value: "Finland" },
  { label: "Denmark", value: "Denmark" },
  { label: "Iceland", value: "Iceland" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Campione d'Italia", value: "Campione d'Italia" },
  { label: "Büsingen am Hochrhein", value: "Büsingen am Hochrhein" },
  {
    label: "Italian exclave of Campione d'Italia",
    value: "Italian exclave of Campione d'Italia",
  },
  { label: "United States", value: "United States" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "East Timor", value: "East Timor" },
  { label: "El Salvador", value: "El Salvador" },
  {
    label: "Federated States of Micronesia",
    value: "Federated States of Micronesia",
  },
];
