export const currencies = [
  { label: "Australian Dollar", value: "Australian Dollar", symbol: "$" },
  {
    label: "British Pound Sterling",
    value: "British Pound Sterling",
    symbol: "£",
  },
  { label: "Canadian Dollar", value: "Canadian Dollar", symbol: "$" },
  { label: "Chinese Yuan", value: "Chinese Yuan", symbol: "¥" },
  { label: "Euro", value: "Euro", symbol: "€" },
  { label: "Indian Rupee", value: "Indian Rupee", symbol: "₹" },
  { label: "Japanese Yen", value: "Japanese Yen", symbol: "¥" },
  { label: "New Zealand Dollar", value: "New Zealand Dollar", symbol: "$" },
  { label: "Swedish Krona", value: "Swedish Krona", symbol: "kr" },
  { label: "Swiss Franc", value: "Swiss Franc", symbol: "CHF" },
  { label: "United States Dollar", value: "United States Dollar", symbol: "$" },
];

// export const currencies = [
//   { label: "AFN - Afghan Afghani", value: "AFN" },
//   { label: "EUR - Euro", value: "EUR" },
//   { label: "ALL - Albanian Lek", value: "ALL" },
//   { label: "DZD - Algerian Dinar", value: "DZD" },
//   { label: "USD - US Dollar", value: "USD" },
//   { label: "AOA - Angolan Kwanza", value: "AOA" },
//   { label: "XCD - East Caribbean Dollar", value: "XCD" },
//   { label: "ARS - Argentine Peso", value: "ARS" },
//   { label: "AMD - Armenian Dram", value: "AMD" },
//   { label: "AWG - Aruban Florin", value: "AWG" },
//   { label: "AUD - Australian Dollar", value: "AUD" },
//   { label: "AZN - Azerbaijani Manat", value: "AZN" },
//   { label: "BSD - Bahamian Dollar", value: "BSD" },
//   { label: "BHD - Bahraini Dinar", value: "BHD" },
//   { label: "BDT - Bangladeshi Taka", value: "BDT" },
//   { label: "BBD - Barbadian Dollar", value: "BBD" },
//   { label: "BYN - Belarusian Ruble", value: "BYN" },
//   { label: "BZD - Belize Dollar", value: "BZD" },
//   { label: "XOF - West African CFA Franc", value: "XOF" },
//   { label: "BMD - Bermudian Dollar", value: "BMD" },
//   { label: "BTN - Bhutanese Ngultrum", value: "BTN" },
//   { label: "BOB - Bolivian Boliviano", value: "BOB" },
//   { label: "BAM - Bosnia and Herzegovina Convertible Mark", value: "BAM" },
//   { label: "BWP - Botswana Pula", value: "BWP" },
//   { label: "NOK - Norwegian Krone", value: "NOK" },
//   { label: "BRL - Brazilian Real", value: "BRL" },
//   { label: "BND - Brunei Dollar", value: "BND" },
//   { label: "BGN - Bulgarian Lev", value: "BGN" },
//   { label: "BIF - Burundian Franc", value: "BIF" },
//   { label: "CVE - Cape Verdean Escudo", value: "CVE" },
//   { label: "KHR - Cambodian Riel", value: "KHR" },
//   { label: "XAF - Central African CFA Franc", value: "XAF" },
//   { label: "CAD - Canadian Dollar", value: "CAD" },
//   { label: "KYD - Cayman Islands Dollar", value: "KYD" },
//   { label: "CLP - Chilean Peso", value: "CLP" },
//   { label: "CNY - Chinese Yuan", value: "CNY" },
//   { label: "COP - Colombian Peso", value: "COP" },
//   { label: "KMF - Comorian Franc", value: "KMF" },
//   { label: "CDF - Congolese Franc", value: "CDF" },
//   { label: "CRC - Costa Rican Colón", value: "CRC" },
//   { label: "HRK - Croatian Kuna", value: "HRK" },
//   { label: "CUP - Cuban Peso", value: "CUP" },
//   { label: "ANG - Netherlands Antillean Guilder", value: "ANG" },
//   { label: "CZK - Czech Koruna", value: "CZK" },
//   { label: "DKK - Danish Krone", value: "DKK" },
//   { label: "DJF - Djiboutian Franc", value: "DJF" },
//   { label: "DOP - Dominican Peso", value: "DOP" },
//   { label: "EGP - Egyptian Pound", value: "EGP" },
//   { label: "ERN - Eritrean Nakfa", value: "ERN" },
//   { label: "SZL - Eswatini Lilangeni", value: "SZL" },
//   { label: "ETB - Ethiopian Birr", value: "ETB" },
//   { label: "FKP - Falkland Islands Pound", value: "FKP" },
//   { label: "FJD - Fijian Dollar", value: "FJD" },
//   { label: "GMD - Gambian Dalasi", value: "GMD" },
//   { label: "GEL - Georgian Lari", value: "GEL" },
//   { label: "GHS - Ghanaian Cedi", value: "GHS" },
//   { label: "GIP - Gibraltar Pound", value: "GIP" },
//   { label: "GTQ - Guatemalan Quetzal", value: "GTQ" },
//   { label: "GNF - Guinean Franc", value: "GNF" },
//   { label: "GYD - Guyanese Dollar", value: "GYD" },
//   { label: "HTG - Haitian Gourde", value: "HTG" },
//   { label: "HNL - Honduran Lempira", value: "HNL" },
//   { label: "HKD - Hong Kong Dollar", value: "HKD" },
//   { label: "HUF - Hungarian Forint", value: "HUF" },
//   { label: "ISK - Icelandic Króna", value: "ISK" },
//   { label: "INR - Indian Rupee", value: "INR" },
//   { label: "IDR - Indonesian Rupiah", value: "IDR" },
//   { label: "IRR - Iranian Rial", value: "IRR" },
//   { label: "IQD - Iraqi Dinar", value: "IQD" },
//   { label: "ILS - Israeli New Shekel", value: "ILS" },
//   { label: "JMD - Jamaican Dollar", value: "JMD" },
//   { label: "JPY - Japanese Yen", value: "JPY" },
//   { label: "JOD - Jordanian Dinar", value: "JOD" },
//   { label: "KZT - Kazakhstani Tenge", value: "KZT" },
//   { label: "KES - Kenyan Shilling", value: "KES" },
//   { label: "KWD - Kuwaiti Dinar", value: "KWD" },
//   { label: "KGS - Kyrgyzstani Som", value: "KGS" },
//   { label: "LAK - Lao Kip", value: "LAK" },
//   { label: "LBP - Lebanese Pound", value: "LBP" },
//   { label: "LSL - Lesotho Loti", value: "LSL" },
//   { label: "LRD - Liberian Dollar", value: "LRD" },
//   { label: "LYD - Libyan Dinar", value: "LYD" },
//   { label: "MOP - Macanese Pataca", value: "MOP" },
//   { label: "MKD - Macedonian Denar", value: "MKD" },
//   { label: "MGA - Malagasy Ariary", value: "MGA" },
//   { label: "MWK - Malawian Kwacha", value: "MWK" },
//   { label: "MYR - Malaysian Ringgit", value: "MYR" },
//   { label: "MVR - Maldivian Rufiyaa", value: "MVR" },
//   { label: "MRU - Mauritanian Ouguiya", value: "MRU" },
//   { label: "MUR - Mauritian Rupee", value: "MUR" },
//   { label: "MXN - Mexican Peso", value: "MXN" },
//   { label: "MDL - Moldovan Leu", value: "MDL" },
//   { label: "MNT - Mongolian Tögrög", value: "MNT" },
//   { label: "MAD - Moroccan Dirham", value: "MAD" },
//   { label: "MZN - Mozambican Metical", value: "MZN" },
//   { label: "MMK - Burmese Kyat", value: "MMK" },
//   { label: "NAD - Namibian Dollar", value: "NAD" },
//   { label: "NPR - Nepalese Rupee", value: "NPR" },
//   { label: "ANG - Netherlands Antillean Guilder", value: "ANG" },
//   { label: "NZD - New Zealand Dollar", value: "NZD" },
//   { label: "NIO - Nicaraguan Córdoba", value: "NIO" },
//   { label: "NGN - Nigerian Naira", value: "NGN" },
//   { label: "KPW - North Korean Won", value: "KPW" },
//   { label: "NOK - Norwegian Krone", value: "NOK" },
//   { label: "OMR - Omani Rial", value: "OMR" },
//   { label: "PKR - Pakistani Rupee", value: "PKR" },
//   { label: "PAB - Panamanian Balboa", value: "PAB" },
//   { label: "PGK - Papua New Guinean Kina", value: "PGK" },
//   { label: "PYG - Paraguayan Guaraní", value: "PYG" },
//   { label: "PEN - Peruvian Sol", value: "PEN" },
//   { label: "PHP - Philippine Peso", value: "PHP" },
//   { label: "PLN - Polish Złoty", value: "PLN" },
//   { label: "QAR - Qatari Riyal", value: "QAR" },
//   { label: "RON - Romanian Leu", value: "RON" },
//   { label: "RUB - Russian Ruble", value: "RUB" },
//   { label: "RWF - Rwandan Franc", value: "RWF" },
//   { label: "SHP - Saint Helena Pound", value: "SHP" },
//   { label: "WST - Samoan Tala", value: "WST" },
//   { label: "STN - São Tomé and Príncipe Dobra", value: "STN" },
//   { label: "SAR - Saudi Riyal", value: "SAR" },
//   { label: "RSD - Serbian Dinar", value: "RSD" },
//   { label: "SCR - Seychellois Rupee", value: "SCR" },
//   { label: "SLL - Sierra Leonean Leone", value: "SLL" },
//   { label: "SGD - Singapore Dollar", value: "SGD" },
//   { label: "SBD - Solomon Islands Dollar", value: "SBD" },
//   { label: "SOS - Somali Shilling", value: "SOS" },
//   { label: "ZAR - South African Rand", value: "ZAR" },
//   { label: "KRW - South Korean Won", value: "KRW" },
//   { label: "SSP - South Sudanese Pound", value: "SSP" },
//   { label: "LKR - Sri Lankan Rupee", value: "LKR" },
//   { label: "SDG - Sudanese Pound", value: "SDG" },
//   { label: "SRD - Surinamese Dollar", value: "SRD" },
//   { label: "SEK - Swedish Krona", value: "SEK" },
//   { label: "CHF - Swiss Franc", value: "CHF" },
//   { label: "SYP - Syrian Pound", value: "SYP" },
//   { label: "TWD - New Taiwan Dollar", value: "TWD" },
//   { label: "TJS - Tajikistani Somoni", value: "TJS" },
//   { label: "TZS - Tanzanian Shilling", value: "TZS" },
//   { label: "THB - Thai Baht", value: "THB" },
//   { label: "TOP - Tongan Paʻanga", value: "TOP" },
//   { label: "TTD - Trinidad and Tobago Dollar", value: "TTD" },
//   { label: "TND - Tunisian Dinar", value: "TND" },
//   { label: "TRY - Turkish Lira", value: "TRY" },
//   { label: "TMT - Turkmenistani Manat", value: "TMT" },
//   { label: "UGX - Ugandan Shilling", value: "UGX" },
//   { label: "UAH - Ukrainian Hryvnia", value: "UAH" },
//   { label: "AED - United Arab Emirates Dirham", value: "AED" },
//   { label: "GBP - British Pound Sterling", value: "GBP" },
//   { label: "UYU - Uruguayan Peso", value: "UYU" },
//   { label: "UZS - Uzbekistani Som", value: "UZS" },
//   { label: "VUV - Vanuatu Vatu", value: "VUV" },
//   { label: "VES - Venezuelan Bolívar", value: "VES" },
//   { label: "VND - Vietnamese Đồng", value: "VND" },
//   { label: "YER - Yemeni Rial", value: "YER" },
//   { label: "ZMW - Zambian Kwacha", value: "ZMW" },
//   { label: "ZWL - Zimbabwean Dollar", value: "ZWL" },
// ];
